#!/bin/sh
# Creates a backup of the SonarQube instance, and copies to repo and S3.
# Two backup files are copied:
# * sonarqube.sql.gz:
#   the SonarQube database backup
# * sonarqube.tar.gz:
#   includes the data directory, which contains the Elasticsearch index backup.
set -eu
SSH_OPTS="-o StrictHostKeyChecking=no"
ssh $SSH_OPTS devops@sonar sonarqube-db backup
files="sonarqube.sql.gz sonarqube.tar.gz"
for file in $files; do
  scp $SSH_OPTS "devops@sonar:/opt/sonar/backups/${file}" .
  aws s3 cp "$file" "s3://scotgovdigitalbackups/sonar/${file}"
  scp $SSH_OPTS "$file" "devops@repo:/srv/backups/services/${file}"
  rm "$file"
done
