#!/bin/sh
set -ex
repo={{repo}}
git="ssh://git@git.digital.gov.uk/mgv/${repo}.git"
{{#maven}}
debian={{debian}}
groupId={{groupId}}
artifactId={{artifactId}}
{{/maven}}

{{#clean}}
{{clean}}
{{/clean}}

git update-ref --no-deref HEAD HEAD
git fetch --tags $git
version=$(make -f debian/rules version)
last=$(git tag -l | grep ^${version} | cut -d- -f2 | sort -nr | head -1)
next=$(( last + 1 ))
version=${version}-${next}
echo "VERSION: $version"

{{#build}}
{{build}}
{{/build}}

git add -f debian/changelog
git commit -m "Build ${version}"
git tag -a -m "Build ${version}" ${version}
git push --tags "${git}" "${version}"

file=$(printf ${debian}_${version}_*.deb)
{{#maven}}
mvn deploy:deploy-file \
    --batch-mode \
    -Dfile="${file}" \
    -DgroupId="${groupId}" \
    -DartifactId="${artifactId}" \
    -Dversion="${version}" \
    -Dpackaging=deb \
    -DrepositoryId=release \
    -Durl=http://nexus/repository/releases/
{{/maven}}
