#!/bin/sh
set -ex
repo={{repo}}
version={{version}}

git clean -fdx
git update-ref --no-deref HEAD HEAD
mvn -B versions:set versions:use-latest-versions \
  -DnewVersion="${version}" \
  -Dincludes='org.mygovscot.*,scot.mygov.*,scot.gov.publishing.*' \
  -DgenerateBackupPoms=false
git commit -am "Set version to ${version}"
git tag -a -m "Build ${version}" ${version}

git push --tags origin "${version}"
mvn -B -Prelease deploy sonar:sonar

{{#snapshot}}
git checkout HEAD^
mvn -B source:jar deploy -DskipTests {{^snapshotAll}}-am -pl {{snapshot}}{{/snapshotAll}}
{{/snapshot}}
