#!/bin/sh
set -ex
repo={{repo}}
{{#maven}}
debian={{debian}}
groupId={{groupId}}
artifactId={{artifactId}}
version={{version}}
{{/maven}}

{{#clean}}
{{clean}}
{{/clean}}

git tag -a -m "Build ${version}" ${version}
git push --tags ssh://git@stash.digital.gov.uk:7999/mgv/${repo}.git "${version}"

{{#build}}
{{build}}
{{/build}}

{{#maven}}
mvn deploy:deploy-file \
    --batch-mode \
    -Dfile="${debian}_${version}_all.deb" \
    -DgroupId="${groupId}" \
    -DartifactId="${artifactId}" \
    -Dversion="${version}" \
    -Dpackaging=deb \
    -DrepositoryId=release \
    -Durl=http://nexus/repository/releases/
{{/maven}}
