#!/bin/sh
set -ex
repo={{repo}}
version="1.0.${BUILD_ID}"

git clean -fdx
git update-ref --no-deref HEAD HEAD
mvn -B versions:set versions:use-latest-versions \
  -DnewVersion="${version}" \
  -Dincludes='org.mygovscot.*,scot.mygov.*' \
  -DgenerateBackupPoms=false
git commit -am "Set version to ${version}"
git tag -a -m "Build ${version}" ${version}

git push --tags ssh://git@stash.digital.gov.uk:7999/mgv/${repo}.git "${version}"
mvn -B -Prelease deploy sonar:sonar

{{#snapshot}}
git checkout HEAD^
mvn -B source:jar deploy -DskipTests {{#snapshot}}-am -pl {{snapshot}}{{/snapshot}}
{{/snapshot}}
