#!/bin/sh -eu

host="${env}${host}.${env}.${domain}"
progname=/opt/checker/checker

set -- /opt/checker/checker
if [ "$stop" = true ]; then
  set -- "$@" "--stop"
fi
set -- "$@" "$type"

echo "Running \`$*\` on ${host}"
echo 'Follow `syslog_program:checker` in Kibana for logs.'

ssh "devops@${host}" \
  sudo systemd-run \
    --unit=checker \
    --collect \
    "$@"
