#!/bin/sh -eu

cat <<'EOF'
Starting maintenance.
Follow `syslog_program: checker` in Kibana for logs.
EOF

ssh devops@${env}${host}.${env}.gov.scot /bin/sh -eu <<EOS
  exec </dev/null >&0 2>&1
  (
    [ "$stop" = true ] && sudo systemctl stop hippo || :
    sudo -iu hippo /opt/checker/run ${type}
    [ "$stop" = true ] && sudo systemctl start hippo || :
  ) | logger -t checker &
EOS
