#!/bin/sh
set -eu

case "${env}" in
  *gv)
    dbrestoreurl="s3://govscotdatabase"
    domain="${env}.gov.scot"
    ;;
  *)
    dbrestoreurl="s3://scotgovdatabase"
    domain="${env}.mygov.scot"
    ;;
esac

pubapp="devops@${env}pubapp01.${domain}"
fbkapp="devops@${env}fbkapp01.${domain}"
redapp="devops@${env}redapp01.${domain}"

ssh "$pubapp" "dbrestoreurl=${dbrestoreurl}" /bin/sh -eu <<'EOF'
dbs=$(ls .credentials | egrep -v template1)
for db in $dbs; do
  dbfrom="${dbrestoreurl}/${db}.zst"
  echo "Restoring ${db} from ${dbfrom}"
  import_db.sh "$dbfrom" "$db" >> "/tmp/${db}.log"
  echo
done
EOF

ssh "$fbkapp" /bin/sh -eu <<'EOF'
echo "Restoring feedback"
restore-couch feedback
EOF

ssh "$redapp" /bin/sh -eu <<'EOF'
echo "Restoring certbot data"
restore-certbot
EOF
