#!/bin/sh
set -eu

case "${env}" in
  *gv)
    dbrestoreurl="s3://govscotdatabase"
    domain="${env}.gov.scot"
    ;;
  *)
    dbrestoreurl="s3://scotgovdatabase"
    domain="${env}.mygov.scot"
    ;;
esac

pubapp="devops@${env}pubapp01.${domain}"
fbkapp="devops@${env}fbkapp01.${domain}"

cmd="ls .credentials | egrep -v template1"
rds_dbs=$(ssh ${pubapp} "${cmd}")

for db in ${rds_dbs}; do
  dbfrom="${dbrestoreurl}/${db}.gz"
  cmd="/usr/local/bin/import_db.sh ${dbfrom} ${db} >> /tmp/${db}.log"
  echo "Restoring ${db} from ${dbfrom}"
  result=$(ssh ${pubapp} "${cmd}")
done

dbrestorefile="feedback.gz"
cmd="/usr/local/bin/import_mongo.sh ${dbrestoreurl} ${dbrestorefile}"
bashcmd="bash -l -c \"${cmd}\""
echo "Restoring feedback from ${dbrestoreurl}"
result=$(ssh ${fbkapp} "${bashcmd}")
