sites:
  - id: mygov
    domain: mygov.scot
    types:
      test:
        up:   'vpc/mygov_build_test.sh ${env} ${ami}'
        down: 'vpc/mygov_teardown_test.sh ${env}_vpc'
      full:
        up:   'vpc/mygov_build_full.sh ${env} ${ami}'
        down: 'vpc/mygov_teardown_full.sh ${env}_vpc'
    environments:
      - name: dev
        type: isis
      - name: int
        type: test
      - name: exp
        type: test
      - name: uat
        type: test
      - name: per
        type: full
      - name: tst
        type: full
      - name: blu
        type: full
      - name: grn
        type: full

  - id: gov
    domain: gov.scot
    types:
      test:
        up:   'vpc/gov_build_test.sh ${env} ${ami}'
        down: 'vpc/gov_teardown_test.sh ${env}_vpc'
      full:
        up:   'vpc/gov_build_full.sh ${env} ${ami}'
        down: 'vpc/gov_teardown_full.sh ${env}_vpc'
    environments:
      - name: dgv
        type: isis
      - name: igv
        type: test
      - name: egv
        type: test
      - name: ugv
        type: test
      - name: pgv
        type: full
      - name: tgv
        type: full
      - name: bgv
        type: full
      - name: ggv
        type: full
