jobs:
  - id: mygov-full-up
    name: Build Full Env
    script: "tools/provisioning/vpc/aws_build_full_env.sh ${env}_vpc"
    parameters:
      - name: env
        description: 'mygov.scot full scale environment'
        options:
          - per
          - blu
          - grn

  - id: mygov-full-down
    name: Teardown Full Env
    script: "tools/provisioning/vpc/aws_teardown_full_env.sh ${env}_vpc"
    parameters:
      - name: env
        description: 'mygov.scot full environment'
        options:
          - per
          - blu
          - grn

  - id: mygov-test-up
    name: Build Test Env
    script: "tools/provisioning/vpc/aws_build_env.sh ${env}_vpc"
    parameters:
      - name: env
        description: 'mygov.scot test environment'
        options:
          - int
          - exp
          - uat

  - id: mygov-test-down
    name: Teardown MyGov Test Env
    script: "tools/provisioning/vpc/aws_teardown_env.sh ${env}_vpc"
    parameters:
      - name: env
        description: 'mygov.scot test environment'
        options:
          - int
          - exp
          - uat

  - id: gov-test-up
    name: Build Gov Scot Test Env
    script: "tools/provisioning/vpc/aws_build_env_govscot.sh ${env}_vpc"
    parameters:
      - name: env
        description: 'gov.scot full scale environment'
        options:
          - igv
          - egv

  - id: gov-test-down
    name: Teardown Gov.Scot Test Env
    script: "tools/provisioning/vpc/aws_teardown_env_govscot.sh ${env}_vpc"
    parameters:
      - name: env
        description: 'gov.scot test environment'
        options:
          - igv
          - egv
