#!/bin/sh -eu

ssh devops@${env}${host}.${env}.gov.scot /bin/sh -eu <<EOS
  export background=${background}
  export clean=${clean}
  migrate ${task}
EOS

echo
echo "For logs, see:"
sed "s/tgv/${env}/g;s/pubapp0./${host}/g;s/'/%27/g;s/)/%29/g" <<'EOT'
https://tgvlog.beta.gov.scot/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:500',display:'5%20seconds',pause:!f,section:1,value:5000),time:(from:now-15m,mode:quick,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:service.keyword,negate:!f,type:phrase,value:migration),query:(match:(service.keyword:(query:migration,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:host.keyword,negate:!f,type:phrase,value:tgvpubapp01),query:(match:(host.keyword:(query:tgvpubapp01,type:phrase))))),index:'logstash-*',interval:auto,query:(match_all:()),sort:!('@timestamp',desc))
EOT
