jobs:
  - name: 'Amphora'
    repo: amphora
    type: java
    snapshot: amphora-client
    host: pubapp01
    site: both
    debian: amphora
    maven: scot.mygov.amphora:amphora-deb

  - name: 'APS Importer'
    repo: aps-importer
    type: java
    host: pubapp01
    site: gov
    debian: aps-importer
    maven: scot.mygov.aps:aps-importer-deb

  - name: 'Assets'
    repo: mygov-assets
    type: node
    publish: true
    sonar: false
    npmjs: true
    mirror: git@github.com:scottishgovernment/mygov-assets.git

  - name: 'Authentication'
    repo: basic-authentication
    type: java
    snapshot: 'authentication-client,authentication-spring'
    host: pubapp01
    site: both
    debian: basic-authentication
    maven: org.mygovscot.beta:authentication-deb

  - name: 'AWS'
    repo: aws
    type: shell
    site: both
    debian: aws
    maven: scot.mygov.infrastructure:aws
    build: './build -v ${version}'

  - name: 'Beta Config'
    repo: beta-config
    type: java
    snapshot: .

  - name: 'Business Rates'
    repo: business-rates-service
    type: java
    host: sitapp01
    site: mygov
    debian: business-rates
    maven: org.mygovscot.business-rates:business-rates-deb

  - name: 'Certbot'
    repo: certbot
    type: upstream
    site: mygov
    debian: certbot
    maven: scot.mygov.upstream:certbot
    build: './build -v ${version}'

  - name: 'Config'
    repo: config
    type: java
    snapshot: .

  - name: 'CSP Report'
    repo: csp-report
    type: shell
    host: fbkapp01
    site: both
    debian: csp-report
    maven: scot.mygov.rubric:csp-report
    build: './build -v ${version}'

  - name: 'Decommission Tool'
    repo: decommission-tool
    type: java
    host: pubapp01
    site: both
    debian: decommission-tool
    maven: org.mygovscot.decommission-tool:decommission-tool-deb

  - name: 'Feedback'
    repo: feedback
    type: java
    host: fbkapp01
    site: both
    debian: feedback
    maven: org.mygovscot.feedback:feedback-deb

  - name: 'Fetchor'
    repo: fetchor
    type: shell
    host: sitwww01
    site: both
    debian: fetchor
    maven: scot.mygov.rubric:fetchor
    build: './build -v ${version}'

  - name: 'Gov Site'
    repo: gov-site
    type: node
    host: pubapp01
    site: gov
    debian: gov-site
    maven: org.mygovscot.beta:gov-site

  - name: 'Gov Scot'
    repo: gov-scot
    type: java
    site: gov
    artifacts:
      gov-scot-cms:
        host: pubapp01
        maven: scot.gov.www:gov-scot-cms-deb
      gov-scot-site:
        host: pubapp01
        maven: scot.gov.www:gov-scot-site-deb

  - name: 'Hippo Libraries'
    repo: hippo-libs
    type: java
    host: pubapp01
    site: gov
    debian: hippo-libs
    maven: scot.mygov.hippo:hippo-libs

  - name: 'Housing'
    repo: housing
    type: java
    host: sitapp01
    site: mygov
    debian: housing
    maven: scot.mygov.housing:housing-deb

  - name: 'Housing Data'
    repo: housing-data
    type: node
    host: pubapp01
    site: mygov
    debian: housing-data
    maven: scot.mygov.housing:housing-data

  - name: 'Json2csv'
    repo: json2csv
    type: node
    host: pubapp01
    site: both
    debian: json2csv
    maven: scot.mygov.rubric:json2csv

  - name: Migration
    repo: migration
    type: java
    host: pubapp01
    site: gov
    debian: migration
    maven: scot.gov.migration:migration-deb

  - name: 'Mygov Forms'
    repo: mygov-forms
    type: java
    host: sitapp01
    site: mygov
    debian: mygov-forms
    maven: scot.mygov.form:mygov-forms-deb

  - name: 'MyGov Site'
    repo: mygov-site
    type: node
    host: pubapp01
    site: mygov
    debian: mygov-site
    maven: org.mygovscot.beta:web-site

  - name: 'Press Releases'
    repo: press-releases
    type: java
    host: pubapp01
    site: gov
    debian: press-releases
    maven: scot.mygov.pressreleases:pressreleases-deb

  - name: 'Proxette'
    repo: proxette
    type: node
    host: pubapp01
    site: both
    debian: proxette
    maven: scot.mygov.rubric:proxette

  - name: 'Publishing'
    repo: beta-publishing
    type: java
    snapshot: publishing-api
    host: pubapp01
    site: both
    debian: publishing
    maven: org.mygovscot.publishing:publishing-deb

  - name: 'Publishing Site'
    repo: publishing-site
    type: node
    host: pubwww01
    site: both
    debian: publishing-site
    maven: org.mygovscot:publishing-site

  - name: 'Puppet Manifests'
    repo: puppet
    type: shell
    site: both
    debian: puppetry
    maven: org.mygovscot.puppet:puppetry
    clean: 'git clean -fdx -e .tmp'
    build: './build -v ${version}'

  - name: 'Search'
    repo: search
    type: java
    host: sitapp01
    site: both
    debian: search
    maven: scot.mygov.search:search-deb

  - name: 'Site Builder'
    repo: site-builder
    type: node
    host: pubapp01
    site: both
    debian: site-builder
    maven: scot.mygov.site:site-builder
    publish: true

  - name: 'Thumbor'
    repo: thumbor
    type: upstream
    host: pubapp01
    site: both
    debian: thumbor
    maven: scot.mygov.upstream:thumbor
    build: './build -v ${version}'

  - name: 'Trigger'
    repo: trigger
    type: node
    host: pubapp01
    site: both
    debian: trigger
    maven: scot.mygov.rubric:trigger

  - name: 'Utils'
    repo: mygovscot_utils
    type: java
    snapshot: ''
