jobs:
  - name: 'AWS'
    repo: aws
    type: shell
    site: both
    debian: aws
    maven: scot.mygov.infrastructure:aws
    build: './build -v ${BUILD_ID}'

  - name: 'Amphora'
    repo: amphora
    type: java
    snapshot: 'amphora-client'
    host: pubapp01
    site: gov
    debian: amphora
    maven: scot.mygov.amphora:amphora-deb

  - name: 'APS Importer'
    repo: aps-importer
    type: java
    host: pubapp01
    site: gov
    debian: aps-importer
    maven: scot.mygov.aps:aps-importer-deb

  - name: 'Authentication'
    repo: basic-authentication
    type: java
    snapshot: 'authentication-client,authentication-spring'
    host: pubapp01
    site: both
    debian: basic-authentication
    maven: org.mygovscot.beta:authentication-deb

  - name: 'Beta Config'
    repo: beta-config
    type: java
    snapshot: ''

  - name: 'Business Rates'
    repo: business-rates-service
    type: java
    host: pubapp01
    site: mygov
    debian: business-rates
    maven: org.mygovscot.business-rates:business-rates-deb

  - name: 'Decommission Tool'
    repo: decommission-tool
    type: java
    host: pubapp01
    site: both
    debian: decommission-tool
    maven: org.mygovscot.decommission-tool:decommission-tool-deb

  - name: 'Doctor'
    repo: doctor
    type: java
    host: pubapp01
    site: both
    debian: doctor
    maven: org.mygovscot.doctor:doctor-deb

  - name: 'Feedback'
    repo: feedback
    type: java
    host: fbkapp01
    site: both
    debian: feedback
    maven: org.mygovscot.feedback:feedback-deb

  - name: 'Funding Tool'
    repo: funding-tool
    type: java
    host: pubapp01
    site: mygov
    debian: funding
    maven: scot.mygov.business.funding:funding-deb

  - name: 'GeoSearch'
    repo: geo-search
    type: java
    host: sitapp01
    site: mygov
    debian: geo-search
    maven: scot.mygov.geosearch:geo-deb

  - name: 'Gov Site'
    repo: gov-site
    type: node
    host: pubapp01
    site: gov
    debian: gov-site
    maven: org.mygovscot.beta:gov-site

  - name: 'Health Check'
    repo: health-check
    type: java
    host: pubapp01
    site: both
    debian: healthcheck
    maven: org.mygovscot.healthcheck:healthcheck-deb

  - name: 'Json2csv'
    repo: json2csv
    type: node
    host: pubapp01
    site: both
    debian: json2csv
    maven: scot.mygov.rubric:json2csv

  - name: 'Marine Service'
    repo: marine-service
    type: java
    host: sitapp01
    site: mygov
    debian: marine-service
    maven: scot.mygov.marine:marine-service-deb

  - name: 'MyGov Site'
    repo: mygov-site
    type: node
    host: pubapp01
    site: mygov
    debian: mygov-site
    maven: org.mygovscot.beta:web-site

  - name: 'Pictor'
    repo: pictor
    type: java
    host: sitapp01
    site: gov
    debian: pictor
    maven: scot.mygov.pictor:pictor-deb

  - name: 'Press Releases'
    repo: press-releases
    type: java
    host: pubapp01
    site: gov
    debian: press-releases
    maven: scot.mygov.pressreleases:pressreleases-deb

  - name: 'Proxette'
    repo: proxette
    type: node
    host: pubapp01
    site: both
    debian: proxette
    maven: scot.mygov.rubric:proxette

  - name: 'Publishing'
    repo: beta-publishing
    type: java
    snapshot: publishing-api
    host: pubapp01
    site: both
    debian: publishing
    maven: org.mygovscot.publishing:publishing-deb

  - name: 'Publishing Site'
    repo: publishing-site
    type: node
    host: pubwww01
    site: both
    debian: publishing-site
    maven: org.mygovscot:publishing-site

  - name: 'Puppet Manifests'
    repo: puppet
    type: shell
    site: both
    debian: puppetry
    maven: org.mygovscot.puppet:puppetry
    build: './build -v ${BUILD_ID}'

  - name: 'Search'
    repo: beta-web-site-search
    type: java
    host: sitapp01
    site: both
    debian: mygov-search
    maven: org.mygovscot.search:search-debian

  - name: 'Site Builder'
    repo: site-builder
    type: node
    host: pubapp01
    site: both
    debian: site-builder
    maven: scot.mygov.site:site-builder

  - name: 'Trigger'
    repo: trigger
    type: node
    host: pubapp01
    site: both
    debian: trigger
    maven: scot.mygov.rubric:trigger

  - name: 'Utils'
    repo: mygovscot_utils
    type: java
    snapshot: ''
