jobs:
  - name: Amphora
    repo: amphora
    type: java
    snapshot: amphora-client
    host: pubapp01
    site: both
    debian: amphora
    maven: scot.mygov.amphora:amphora-deb

  - name: Authentication
    repo: basic-authentication
    type: java
    snapshot: 'authentication-api,authentication-client,authentication-spring'
    host: pubapp01
    site: both
    debian: basic-authentication
    maven: org.mygovscot.beta:authentication-deb

  - name: AWS
    repo: aws
    type: shell
    site: both
    debian: aws
    maven: scot.mygov.infrastructure:aws
    build: './build -v ${version}'

  - name: Beta Config
    repo: beta-config
    type: java
    snapshot: .

  - name: Business Rates
    repo: business-rates-service
    type: java
    host: sitapp01
    site: mygov
    debian: business-rates
    maven: org.mygovscot.business-rates:business-rates-deb
    mirror: git@github.com:scottishgovernment/business-rates.git

  - name: Checker
    repo: hippo-checker
    type: java
    host: pubapp01
    site: gov
    debian: checker
    maven: scot.gov.hippo:checker-deb
    mirror: git@github.com:scottishgovernment/hippo-checker.git

  - name: Config
    repo: config
    type: java
    snapshot: .

  - name: Hippo plugins
    repo: hippo-govscot
    type: java
    snapshot: 'hippo-govscot-hst,hippo-govscot-hst-funnelback,hippo-govscot-platform-funnelback,hippo-govscot-cms-funnelback'

  - name: CSP Report
    repo: csp-report
    type: node
    host: fbkapp01
    site: both
    debian: csp-report
    maven: scot.mygov.rubric:csp-report

  - name: Decommission Tool
    repo: decommission-tool
    type: java
    host: pubapp01
    site: mygov
    debian: decommission-tool
    maven: org.mygovscot.decommission-tool:decommission-tool-deb

  - name: Decommissioned Sites
    repo: decommissioned-sites
    type: node
    host: pubapp01
    site: mygov
    debian: decommissioned-sites
    maven: scot.mygov.redirects:decommissioned-sites
    mirror: git@github.com:scottishgovernment/decommissioned-sites.git

  - name: Feedback
    repo: feedback
    type: java
    host: fbkapp01
    site: both
    debian: feedback
    maven: org.mygovscot.feedback:feedback-deb

  - name: Fetchor
    repo: fetchor
    type: shell
    host: sitwww01
    site: mygov
    debian: fetchor
    maven: scot.mygov.rubric:fetchor
    build: './build -v ${version}'

  - name: Gov Scot
    repo: gov-scot
    type: java
    site: gov
    artifacts:
      gov-scot-cms:
        hosts:
          - pubapp01
        maven: scot.gov.www:gov-scot-cms-deb
      gov-scot-site:
        hosts:
          - pubapp01
          - sitapp01
        maven: scot.gov.www:gov-scot-site-deb
      gov-scot-repo:
        hosts:
          - sitapp01
        maven: scot.gov.www:gov-scot-repository-deb
      gov-scot-libs:
        hosts:
          - pubapp01
          - sitapp01
        maven: scot.gov.www:gov-scot-libs
    mirror: git@github.com:scottishgovernment/gov-scot.git

  - name: Housing
    repo: housing
    type: java
    host: sitapp01
    site: mygov
    debian: housing
    maven: scot.mygov.housing:housing-deb
    mirror: git@github.com:scottishgovernment/housing.git

  - name: Housing Data
    repo: housing-data
    type: node
    host: pubapp01
    site: mygov
    debian: housing-data
    maven: scot.mygov.housing:housing-data
    mirror: git@github.com:scottishgovernment/housing-data.git

  - name: Jolokia
    repo: jolokia
    type: java
    site: both
    artifacts:
      jolokia:
        hosts:
          - pubapp01
          - sitapp01
        maven: scot.mygov.upstream.jolokia:jolokia-deb

  - name: Json2csv
    repo: json2csv
    type: node
    host: pubapp01
    site: both
    debian: json2csv
    maven: scot.mygov.rubric:json2csv

  - name: Migration
    repo: migration
    type: java
    host: pubapp01
    site: both
    debian: migration
    maven: scot.gov.migration:migration-deb

  - name: Mygov Forms
    repo: mygov-forms
    type: java
    host: sitapp01
    site: mygov
    debian: mygov-forms
    maven: scot.mygov.form:mygov-forms-deb

  - name: Pattern Library
    repo: pattern-library
    version: 0.0.${BUILD_ID}
    type: node
    sonar: false
    npmjs: true
    mirror: git@github.com:scottishgovernment/pattern-library.git

  - name: Payment
    repo: payment
    type: java
    host: sitapp01
    site: gov
    debian: payment
    maven: scot.gov.publishing.payment:payment-deb
    mirror: git@github.com:scottishgovernment/payment.git

  - name: Press Releases
    repo: press-releases
    type: java
    host: pubapp01
    site: gov
    debian: press-releases
    maven: scot.mygov.pressreleases:pressreleases-deb

  - name: Proxette
    repo: proxette
    type: node
    host: pubapp01
    site: both
    debian: proxette
    maven: scot.mygov.rubric:proxette

  - name: Publications
    repo: publications
    type: java
    host: pubapp01
    site: gov
    debian: publications
    maven: scot.gov.publications:publications-deb
    mirror: git@github.com:scottishgovernment/publications.git

  - name: Publishing
    repo: publishing
    type: java
    site: mygov
    artifacts:
      publishing-cms:
        hosts:
          - pubapp01
        maven: scot.mygov.publishing:publishing-cms-deb
      publishing-site:
        hosts:
          - pubapp01
          - sitapp01
        maven: scot.mygov.publishing:publishing-site-deb
      publishing-platform:
        hosts:
          - sitapp01
        maven: scot.mygov.publishing:publishing-platform-deb
      publishing-libs:
        hosts:
          - pubapp01
          - sitapp01
        maven: scot.mygov.publishing:publishing-libs
    mirror: git@github.com:scottishgovernment/publishing.git

  - name: Puppet Manifests
    repo: puppet
    type: shell
    site: both
    debian: puppetry
    maven: org.mygovscot.puppet:puppetry
    clean: 'git clean -fdx -e .tmp'
    build: './build -v ${version}'

  - name: Rubric Site
    repo: publishing-site
    type: node
    host: pubwww01
    site: both
    debian: rubric-site
    maven: org.mygovscot:publishing-site

  - name: Utils
    repo: mygovscot_utils
    type: java
    snapshot: ''
