#!/bin/sh
# Set the next build number for jobs
set -e

aws s3 cp s3://mgs-jenkins/versions.json versions.json
jq -r 'to_entries[] | .key + " " + (.value | tostring)' versions.json > versions.txt

# Change to 'jobs' directory, i.e. the parent directory of all jobs.
cd ../..

while read project version; do
  mkdir -p "$project"
  file="$project/nextBuildNumber"
  if [ ! -r "$file" ] || [ "$(cat $file)" -lt "$version" ]; then
    echo $version > $file
  fi
done < "$OLDPWD/versions.txt"

echo
echo "Build versions set: reload Jenkins to see changes."
echo
